from .seedance_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .omnihuman_nodes import OMNIHUMAN_NODE_CLASS_MAPPINGS, OMNIHUMAN_NODE_DISPLAY_NAME_MAPPINGS

# Merge all node mappings
ALL_NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **OMNIHUMAN_NODE_CLASS_MAPPINGS}
ALL_NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **OMNIHUMAN_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

# Export the merged mappings with the expected names for ComfyUI
NODE_CLASS_MAPPINGS = ALL_NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = ALL_NODE_DISPLAY_NAME_MAPPINGS
